language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
    - $HOME/.mongodb-binaries
env:
  global:
    secure: laRiVUTV5mTxHXoo/Jn4o20Mja587OnP/Csxrxs4mpHjLM7xac53lz/nGicOruHJVBRsbTjBjk+9RgQMW7uNWYrzt5Ed/HkqD/2Fvd3ZA0WpcxyAivCwy1CcIVTCtcLxrMFsNEO7DWgvIGh6+JiSwc0HbfsTk7kNM0LDHPRQapdDxSP2ubYj8GYrYUlpfbq+dhCLSgAPQkPrsCTlNNBdl0cg6RMxxuD1zrHNBALJaUu7sStGzSp20OcWRlENne50+tgeTv1lozxG5Q8PlAU/IW1cypg1aFslMCH4QYjXM0fXs4Q2FkWYxJmabmWfAIWXwIc8w+ld1z7oGtXEFzJbfrEFVBCcL3IuQPsTXkkA6GwKaT41Ys17nxFacKezx68XKBMX9AhuaLyxtTw3hUU63+9dPjUBD3mg7wjOe3AWw3ZXoWiX8YOoryCmQa5vqnhEW4wT2iTeT6/80TiCvTbVsOG9Ww3FFRCTal4qms8LKZODGXrKuFinKF36KqaDLoD7P5BKZmJTfxXTGYluM7VREV4hsIbRJ2XYIqYljna/1lC7oY7SsWKOJ5QWC5xitPMYDyX2x5xqh7v3OwIQh0aXwFDzf67ymOSbjYcMdDtQFFvd/fyqscoDXmAKfC4tLWmwlHlweFuRlg+VcjZguGBHfurIbsa3aLZub4krXws+T5o=
install:
  - yarn install
  - yarn bootstrap
script:
  - yarn build
after_script:
  - yarn coverage && nyc report --reporter=text-lcov | coveralls
deploy:
  provider: script
  script: bash script/publish
  skip_cleanup: true
  on:
    tags: true
