language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
  - "$HOME/.mongodb-binaries"
env:
  global:
  - secure: FV/2xKNZ5C61aT4K6cFHtJNuQqK1Sk2xA/NqtJ6Dj0/x0JxsZk42yB7xLHoWSQ5ozbukkZxkuvuS6ta/pg02U7fDebQIrtRSCXXV4No51KPrRwpuekstgUficwrNMaamLU3jxJxTPfx28vT9k89qhai2THT9RNVlYxWbnDcZfmWk24MuPlTpjEP/u8m7jHp+AVQKq6PGo0iW6XSpyu5ayD3T8xiRi90SPrzDupTIBmcWW84loqGMxxf171FlYfJLe0mf56w4X+TU+lq1e5sPwnZdR6yZsTSA7//A3bC9rq75DSiaXjrprtOyTiVVjmM0/unlgyyjbB8ZFO+ZpPnZDAb4mEdmeU4sITCiKEjYUpCVmkrOQuoh24DJIZUzJbioS4HXb4CwVP+OJJDTGASRtft+SPctfVFoxWRe5wLKqtifAgsf4mhNBgVXsyxAm13WfIOe/T170OuoLbFu00PdFXgXu9LVtOJSoTkmRHte+iKaPq6/82ehWja/7r35e1b/VDJS+E+ziygaqUqC3HaMv6ex7/8SzqVLzD1wk1XD8+QIgWsLfhcUEtWIwDJPMafUejMLu2j8WUkmMftBqvKwexVWaXLfqlEMeggQBAOW2DZQ7e6ccGRhgIIdHcQENKNCwR2DZd4nW9/eVOLBftkCjOoxqjMlkG7d8OAVZu1oY08=
install:
- yarn install
- yarn bootstrap
script:
- yarn build
after_script:
- yarn coverage && nyc report --reporter=text-lcov | coveralls
deploy:
  provider: script
  script: bash .scripts/publish
  skip_cleanup: true
  on:
    tags: true
