language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
before_install:
  - chmod +x ./.scripts/release.sh
install:
  - yarn install
  - yarn bootstrap
script:
  - yarn build
after_script:
  - yarn coverage && nyc report --reporter=text-lcov | coveralls
deploy:
  provider: npm
  email: christo@cryptodrunks.net
  skip_cleanup: true
  on:
    tags: true
