#!/bin/bash

CMD=$1
shift

exe() { echo "$@" ; $@ ; }

DIST="lib"

case $CMD in
  clean)
    exe "../../node_modules/.bin/rimraf $DIST"
    ;;

  compile)
    exe "../../node_modules/.bin/babel --config-file $(pwd)/.babelrc.js --verbose -d $DIST ./src"
    ;;

  test)
    if [ -d "./test" ]; then
      exe "../../node_modules/.bin/ava"
    else
      echo "No tests to run"
    fi
    ;;

  lint)
    exe "../../node_modules/.bin/eslint ./src ./test -c $(pwd)/.eslintrc.js --report-unused-disable-directives"
    ;;

  fix)
    exe "../../node_modules/.bin/eslint ./src ./test -c $(pwd)/.eslintrc.js --report-unused-disable-directives --fix"
    ;;

  flow)
    exe "../../node_modules/.bin/flow"
    ;;

  *)
    if [[ -z "$CMD" ]]; then
      echo "USAGE: ./task (clean|compile|test|lint|<node_modules_bin_command>) command_args"
      exit 0
    fi
    exe "../../node_modules/.bin/$CMD" "$@"
    ;;
esac
